//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamGridManager.Frontend.WindowsFormsApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong SteamUserID {
            get {
                return ((ulong)(this["SteamUserID"]));
            }
            set {
                this["SteamUserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SteamAppPath {
            get {
                return ((string)(this["SteamAppPath"]));
            }
            set {
                this["SteamAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong AppID {
            get {
                return ((ulong)(this["AppID"]));
            }
            set {
                this["AppID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool View_Show_LibraryCapsule {
            get {
                return ((bool)(this["View_Show_LibraryCapsule"]));
            }
            set {
                this["View_Show_LibraryCapsule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool View_Show_HeroGraphic {
            get {
                return ((bool)(this["View_Show_HeroGraphic"]));
            }
            set {
                this["View_Show_HeroGraphic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool View_Show_Logo {
            get {
                return ((bool)(this["View_Show_Logo"]));
            }
            set {
                this["View_Show_Logo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool View_Show_Header {
            get {
                return ((bool)(this["View_Show_Header"]));
            }
            set {
                this["View_Show_Header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool View_Show_Icon {
            get {
                return ((bool)(this["View_Show_Icon"]));
            }
            set {
                this["View_Show_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool View_UseAlternateColumnHeaders {
            get {
                return ((bool)(this["View_UseAlternateColumnHeaders"]));
            }
            set {
                this["View_UseAlternateColumnHeaders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserData")]
        public global::SteamGridManager.CacheLocation List_CacheLocation {
            get {
                return ((global::SteamGridManager.CacheLocation)(this["List_CacheLocation"]));
            }
            set {
                this["List_CacheLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string View_Overlay_LibraryCapsule {
            get {
                return ((string)(this["View_Overlay_LibraryCapsule"]));
            }
            set {
                this["View_Overlay_LibraryCapsule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string View_Overlay_HeroGraphic {
            get {
                return ((string)(this["View_Overlay_HeroGraphic"]));
            }
            set {
                this["View_Overlay_HeroGraphic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string View_Overlay_Logo {
            get {
                return ((string)(this["View_Overlay_Logo"]));
            }
            set {
                this["View_Overlay_Logo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string View_Overlay_Header {
            get {
                return ((string)(this["View_Overlay_Header"]));
            }
            set {
                this["View_Overlay_Header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string View_Overlay_Icon {
            get {
                return ((string)(this["View_Overlay_Icon"]));
            }
            set {
                this["View_Overlay_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Title=Run Application\nLocation=steam://rungameid/${AppID}\nArguments=\nStart" +
            "ingDirectory=\nVerb=Run\nAssetTypeNames=none,capsule,hero,logo,header,icon\n</strin" +
            "g>\r\n  <string>Title=Run\nLocation=steam://run/${AppID}\nArguments=\nStartingDirecto" +
            "ry=\nVerb=Run\nAssetTypeNames=none,capsule,hero,logo,header,icon\n</string>\r\n  <str" +
            "ing>Title=Run in Safe Mode\nLocation=steam://runsafe/${AppID}\nArguments=\nStarting" +
            "Directory=\nVerb=Run\nAssetTypeNames=none,capsule,hero,logo,header,icon\n</string>\r" +
            "\n  <string>Title=Show Keys\nLocation=steam://cdkeys/${AppID}\nArguments=\nStartingD" +
            "irectory=\nVerb=Run\nAssetTypeNames=none,capsule,hero,logo,header,icon\n</string>\r\n" +
            "  <string>Title=Check System Requirements\nLocation=steam://checksysreqs/${AppID}" +
            "\nArguments=\nStartingDirectory=\nVerb=Run\nAssetTypeNames=none,capsule,hero,logo,he" +
            "ader,icon\n</string>\r\n  <string>Title=Install\nLocation=steam://install/${AppID}\nA" +
            "rguments=\nStartingDirectory=\nVerb=Run\nAssetTypeNames=none,capsule,hero,logo,head" +
            "er,icon\n</string>\r\n  <string>Title=Uninstall\nLocation=steam://uninstall/${AppID}" +
            "\nArguments=\nStartingDirectory=\nVerb=Run\nAssetTypeNames=none,capsule,hero,logo,he" +
            "ader,icon\n</string>\r\n  <string>Title=Validate Game Files\nLocation=steam://valida" +
            "te/${AppID}\nArguments=\nStartingDirectory=\nVerb=Run\nAssetTypeNames=none,capsule,h" +
            "ero,logo,header,icon\n</string>\r\n  <string>Title=Defragment Game Files\nLocation=s" +
            "team://defrag/${AppID}\nArguments=\nStartingDirectory=\nVerb=Run\nAssetTypeNames=non" +
            "e,capsule,hero,logo,header,icon\n</string>\r\n  <string>Title=Backup\nLocation=steam" +
            "://backup/${AppID}\nArguments=\nStartingDirectory=\nVerb=Run\nAssetTypeNames=none,ca" +
            "psule,hero,logo,header,icon\n</string>\r\n  <string>Title=Preload\nLocation=steam://" +
            "preload/${AppID}\nArguments=\nStartingDirectory=\nVerb=Run\nAssetTypeNames=none,caps" +
            "ule,hero,logo,header,icon\n</string>\r\n  <string>Title=Force Input\nLocation=steam:" +
            "//forceinputappid/${AppID}\nArguments=\nStartingDirectory=\nVerb=Run\nAssetTypeNames" +
            "=none,capsule,hero,logo,header,icon\n</string>\r\n  <string>Title=Details\nLocation=" +
            "steam://nav/games/details/${AppID}\nArguments=\nStartingDirectory=\nVerb=Run\nAssetT" +
            "ypeNames=none,capsule,hero,logo,header,icon\n</string>\r\n  <string>Title=Game Hub\n" +
            "Location=steam://url/GameHub/${AppID}\nArguments=\nStartingDirectory=\nVerb=Run\nAss" +
            "etTypeNames=none,capsule,hero,logo,header,icon\n</string>\r\n  <string>Title=Worksh" +
            "op\nLocation=steam://url/SteamWorkshopPage/${AppID}\nArguments=\nStartingDirectory=" +
            "\nVerb=Run\nAssetTypeNames=none,capsule,hero,logo,header,icon\n</string>\r\n  <string" +
            ">Title=Achievements\nLocation=steam://url/SteamIDAchievementsPage/${AppID}\nArgume" +
            "nts=\nStartingDirectory=\nVerb=Run\nAssetTypeNames=none,capsule,hero,logo,header,ic" +
            "on\n</string>\r\n  <string>Title=Open Screenshots\nLocation=steam://open/screenshots" +
            "/${AppID}\nArguments=\nStartingDirectory=\nVerb=Run\nAssetTypeNames=none,capsule,her" +
            "o,logo,header,icon\n</string>\r\n  <string>Title=Friends That Play\nLocation=steam:/" +
            "/url/CommunityFriendsThatPlay/${AppID}\nArguments=\nStartingDirectory=\nVerb=Run\nAs" +
            "setTypeNames=none,capsule,hero,logo,header,icon\n</string>\r\n  <string>Title=Adver" +
            "tise\nLocation=steam://advertise/${AppID}\nArguments=\nStartingDirectory=\nVerb=Run\n" +
            "AssetTypeNames=none,capsule,hero,logo,header,icon\n</string>\r\n  <string>Title=Sto" +
            "re\nLocation=steam://store/${AppID}\nArguments=\nStartingDirectory=\nVerb=Run\nAssetT" +
            "ypeNames=none,capsule,hero,logo,header,icon\n</string>\r\n  <string>Title=News\nLoca" +
            "tion=steam://appnews/${AppID}\nArguments=\nStartingDirectory=\nVerb=Run\nAssetTypeNa" +
            "mes=none,capsule,hero,logo,header,icon\n</string>\r\n  <string>Title=Update News\nLo" +
            "cation=steam://updatenews/${AppID}\nArguments=\nStartingDirectory=\nVerb=Run\nAssetT" +
            "ypeNames=none,capsule,hero,logo,header,icon\n</string>\r\n  <string>Title=Event Ann" +
            "ouncements\nLocation=steam://url/EventAnnouncementPage/${AppID}/1\nArguments=\nStar" +
            "tingDirectory=\nVerb=Run\nAssetTypeNames=none,capsule,hero,logo,header,icon\n</stri" +
            "ng>\r\n  <string>Title=Store App Page\nLocation=steam://url/StoreAppPage/${AppID}\nA" +
            "rguments=\nStartingDirectory=\nVerb=Run\nAssetTypeNames=none,capsule,hero,logo,head" +
            "er,icon\n</string>\r\n  <string>Title=Store DLC Page\nLocation=steam://url/StoreDLCP" +
            "age/${AppID}\nArguments=\nStartingDirectory=\nVerb=Run\nAssetTypeNames=none,capsule," +
            "hero,logo,header,icon\n</string>\r\n  <string>Title=Purchase\nLocation=steam://purch" +
            "ase/${AppID}\nArguments=\nStartingDirectory=\nVerb=Run\nAssetTypeNames=none,capsule," +
            "hero,logo,header,icon\n</string>\r\n  <string>Title=Refresh Configuration\nLocation=" +
            "steam://flushconfig/\nArguments=\nStartingDirectory=\nVerb=Run\nAssetTypeNames=none," +
            "capsule,hero,logo,header,icon\n</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ExternalApplications {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExternalApplications"]));
            }
            set {
                this["ExternalApplications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::SteamGridManager.AssetAction Details_Asset_MouseLeftClickAction {
            get {
                return ((global::SteamGridManager.AssetAction)(this["Details_Asset_MouseLeftClickAction"]));
            }
            set {
                this["Details_Asset_MouseLeftClickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Preview")]
        public global::SteamGridManager.AssetAction Details_Asset_MouseLeftDoubleClickAction {
            get {
                return ((global::SteamGridManager.AssetAction)(this["Details_Asset_MouseLeftDoubleClickAction"]));
            }
            set {
                this["Details_Asset_MouseLeftDoubleClickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::SteamGridManager.AssetAction Details_Asset_MouseMiddleClickAction {
            get {
                return ((global::SteamGridManager.AssetAction)(this["Details_Asset_MouseMiddleClickAction"]));
            }
            set {
                this["Details_Asset_MouseMiddleClickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Open")]
        public global::SteamGridManager.AssetAction Details_Asset_MouseMiddleDoubleClickAction {
            get {
                return ((global::SteamGridManager.AssetAction)(this["Details_Asset_MouseMiddleDoubleClickAction"]));
            }
            set {
                this["Details_Asset_MouseMiddleDoubleClickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Details_Asset_Preview_BackColor {
            get {
                return ((global::System.Drawing.Color)(this["Details_Asset_Preview_BackColor"]));
            }
            set {
                this["Details_Asset_Preview_BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Details_Asset_Preview_BackColor_CustomColors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Details_Asset_Preview_BackColor_CustomColors"]));
            }
            set {
                this["Details_Asset_Preview_BackColor_CustomColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("✓")]
        public string List_Assets_Exist_String {
            get {
                return ((string)(this["List_Assets_Exist_String"]));
            }
            set {
                this["List_Assets_Exist_String"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("✗")]
        public string List_Assets_Missing_String {
            get {
                return ((string)(this["List_Assets_Missing_String"]));
            }
            set {
                this["List_Assets_Missing_String"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color List_Assets_Exist_Color {
            get {
                return ((global::System.Drawing.Color)(this["List_Assets_Exist_Color"]));
            }
            set {
                this["List_Assets_Exist_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color List_Assets_Missing_Color {
            get {
                return ((global::System.Drawing.Color)(this["List_Assets_Missing_Color"]));
            }
            set {
                this["List_Assets_Missing_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartupCacheLocation {
            get {
                return ((string)(this["StartupCacheLocation"]));
            }
            set {
                this["StartupCacheLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NonSteamAppIconCachePath {
            get {
                return ((string)(this["NonSteamAppIconCachePath"]));
            }
            set {
                this["NonSteamAppIconCachePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowProgramsAsIcon {
            get {
                return ((bool)(this["AllowProgramsAsIcon"]));
            }
            set {
                this["AllowProgramsAsIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupPath {
            get {
                return ((string)(this["BackupPath"]));
            }
            set {
                this["BackupPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0.0")]
        public string ConfigurationVersion {
            get {
                return ((string)(this["ConfigurationVersion"]));
            }
            set {
                this["ConfigurationVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoDownloadMissingAssets {
            get {
                return ((bool)(this["AutoDownloadMissingAssets"]));
            }
            set {
                this["AutoDownloadMissingAssets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserData, LibraryCache")]
        public global::SteamGridManager.CacheLocation Details_CacheLocation {
            get {
                return ((global::SteamGridManager.CacheLocation)(this["Details_CacheLocation"]));
            }
            set {
                this["Details_CacheLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65536")]
        public long Details_Progress_MinFileSizeThreshold {
            get {
                return ((long)(this["Details_Progress_MinFileSizeThreshold"]));
            }
            set {
                this["Details_Progress_MinFileSizeThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection Toggles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Toggles"]));
            }
            set {
                this["Toggles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsReady {
            get {
                return ((bool)(this["IsReady"]));
            }
            set {
                this["IsReady"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Title")]
        public global::SteamGridManager.ColumnHeaderType View_List_SortBy {
            get {
                return ((global::SteamGridManager.ColumnHeaderType)(this["View_List_SortBy"]));
            }
            set {
                this["View_List_SortBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.SortOrder View_List_SortOrder {
            get {
                return ((global::System.Windows.Forms.SortOrder)(this["View_List_SortOrder"]));
            }
            set {
                this["View_List_SortOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string View_List_Filter {
            get {
                return ((string)(this["View_List_Filter"]));
            }
            set {
                this["View_List_Filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CustomColors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomColors"]));
            }
            set {
                this["CustomColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Details_UserData_LibraryCapsule_BackColor {
            get {
                return ((global::System.Drawing.Color)(this["Details_UserData_LibraryCapsule_BackColor"]));
            }
            set {
                this["Details_UserData_LibraryCapsule_BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Details_UserData_HeroGraphic_BackColor {
            get {
                return ((global::System.Drawing.Color)(this["Details_UserData_HeroGraphic_BackColor"]));
            }
            set {
                this["Details_UserData_HeroGraphic_BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Details_UserData_Logo_BackColor {
            get {
                return ((global::System.Drawing.Color)(this["Details_UserData_Logo_BackColor"]));
            }
            set {
                this["Details_UserData_Logo_BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Details_UserData_Header_BackColor {
            get {
                return ((global::System.Drawing.Color)(this["Details_UserData_Header_BackColor"]));
            }
            set {
                this["Details_UserData_Header_BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Details_UserData_Icon_BackColor {
            get {
                return ((global::System.Drawing.Color)(this["Details_UserData_Icon_BackColor"]));
            }
            set {
                this["Details_UserData_Icon_BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Details_LibraryCache_LibraryCapsule_BackColor {
            get {
                return ((global::System.Drawing.Color)(this["Details_LibraryCache_LibraryCapsule_BackColor"]));
            }
            set {
                this["Details_LibraryCache_LibraryCapsule_BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Details_LibraryCache_HeroGraphic_BackColor {
            get {
                return ((global::System.Drawing.Color)(this["Details_LibraryCache_HeroGraphic_BackColor"]));
            }
            set {
                this["Details_LibraryCache_HeroGraphic_BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Details_LibraryCache_Logo_BackColor {
            get {
                return ((global::System.Drawing.Color)(this["Details_LibraryCache_Logo_BackColor"]));
            }
            set {
                this["Details_LibraryCache_Logo_BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Details_LibraryCache_Header_BackColor {
            get {
                return ((global::System.Drawing.Color)(this["Details_LibraryCache_Header_BackColor"]));
            }
            set {
                this["Details_LibraryCache_Header_BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Details_LibraryCache_Icon_BackColor {
            get {
                return ((global::System.Drawing.Color)(this["Details_LibraryCache_Icon_BackColor"]));
            }
            set {
                this["Details_LibraryCache_Icon_BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool View_StatusBar_Show {
            get {
                return ((bool)(this["View_StatusBar_Show"]));
            }
            set {
                this["View_StatusBar_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Database_AppInfo_LoadAtStart {
            get {
                return ((bool)(this["Database_AppInfo_LoadAtStart"]));
            }
            set {
                this["Database_AppInfo_LoadAtStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Database_Shortcuts_LoadAtStart {
            get {
                return ((bool)(this["Database_Shortcuts_LoadAtStart"]));
            }
            set {
                this["Database_Shortcuts_LoadAtStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PropertiesDialog_StartMaximized {
            get {
                return ((bool)(this["PropertiesDialog_StartMaximized"]));
            }
            set {
                this["PropertiesDialog_StartMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Properties")]
        public global::SteamGridManager.AppAction List_AppAction {
            get {
                return ((global::SteamGridManager.AppAction)(this["List_AppAction"]));
            }
            set {
                this["List_AppAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vdf:")]
        public string List_VdfFilter_Prefix {
            get {
                return ((string)(this["List_VdfFilter_Prefix"]));
            }
            set {
                this["List_VdfFilter_Prefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int List_Column_AppID_MinAutoWidth {
            get {
                return ((int)(this["List_Column_AppID_MinAutoWidth"]));
            }
            set {
                this["List_Column_AppID_MinAutoWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public int List_Column_AppID_MaxAutoWidth {
            get {
                return ((int)(this["List_Column_AppID_MaxAutoWidth"]));
            }
            set {
                this["List_Column_AppID_MaxAutoWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int List_Column_Title_MinAutoWidth {
            get {
                return ((int)(this["List_Column_Title_MinAutoWidth"]));
            }
            set {
                this["List_Column_Title_MinAutoWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int List_Column_Title_MaxAutoWidth {
            get {
                return ((int)(this["List_Column_Title_MaxAutoWidth"]));
            }
            set {
                this["List_Column_Title_MaxAutoWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool List_Filter_RestoreAtStart {
            get {
                return ((bool)(this["List_Filter_RestoreAtStart"]));
            }
            set {
                this["List_Filter_RestoreAtStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ToggleImageSizeMode")]
        public global::SteamGridManager.PreviewAction Details_Asset_Preview_MouseLeftDoubleClickAction {
            get {
                return ((global::SteamGridManager.PreviewAction)(this["Details_Asset_Preview_MouseLeftDoubleClickAction"]));
            }
            set {
                this["Details_Asset_Preview_MouseLeftDoubleClickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Close")]
        public global::SteamGridManager.PreviewAction Details_Asset_Preview_MouseMiddleClickAction {
            get {
                return ((global::SteamGridManager.PreviewAction)(this["Details_Asset_Preview_MouseMiddleClickAction"]));
            }
            set {
                this["Details_Asset_Preview_MouseMiddleClickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ChooseBackgroundColor")]
        public global::SteamGridManager.PreviewAction Details_Asset_Preview_MouseRightClickAction {
            get {
                return ((global::SteamGridManager.PreviewAction)(this["Details_Asset_Preview_MouseRightClickAction"]));
            }
            set {
                this["Details_Asset_Preview_MouseRightClickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::SteamGridManager.PreviewAction Details_Asset_Preview_MouseLeftClickAction {
            get {
                return ((global::SteamGridManager.PreviewAction)(this["Details_Asset_Preview_MouseLeftClickAction"]));
            }
            set {
                this["Details_Asset_Preview_MouseLeftClickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::SteamGridManager.PreviewAction Details_Asset_Preview_MouseMiddleDoubleClickAction {
            get {
                return ((global::SteamGridManager.PreviewAction)(this["Details_Asset_Preview_MouseMiddleDoubleClickAction"]));
            }
            set {
                this["Details_Asset_Preview_MouseMiddleDoubleClickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::SteamGridManager.PreviewAction Details_Asset_Preview_MouseRightDoubleClickAction {
            get {
                return ((global::SteamGridManager.PreviewAction)(this["Details_Asset_Preview_MouseRightDoubleClickAction"]));
            }
            set {
                this["Details_Asset_Preview_MouseRightDoubleClickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection List_Column_Order {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["List_Column_Order"]));
            }
            set {
                this["List_Column_Order"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection List_Column_Types {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["List_Column_Types"]));
            }
            set {
                this["List_Column_Types"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color VdfDefinition_Object_Color {
            get {
                return ((global::System.Drawing.Color)(this["VdfDefinition_Object_Color"]));
            }
            set {
                this["VdfDefinition_Object_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PropertyEditor_PersistTextSettings {
            get {
                return ((bool)(this["PropertyEditor_PersistTextSettings"]));
            }
            set {
                this["PropertyEditor_PersistTextSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PropertyEditor_AllowTabs {
            get {
                return ((bool)(this["PropertyEditor_AllowTabs"]));
            }
            set {
                this["PropertyEditor_AllowTabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PropertyEditor_AllowNewLines {
            get {
                return ((bool)(this["PropertyEditor_AllowNewLines"]));
            }
            set {
                this["PropertyEditor_AllowNewLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool List_VdfFilter_UseRegularExpressions {
            get {
                return ((bool)(this["List_VdfFilter_UseRegularExpressions"]));
            }
            set {
                this["List_VdfFilter_UseRegularExpressions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool List_VdfFilter_MatchCase {
            get {
                return ((bool)(this["List_VdfFilter_MatchCase"]));
            }
            set {
                this["List_VdfFilter_MatchCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool List_VdfFilter_MatchWholeWord {
            get {
                return ((bool)(this["List_VdfFilter_MatchWholeWord"]));
            }
            set {
                this["List_VdfFilter_MatchWholeWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>appinfo</string>
  <string>appinfo/common</string>
  <string>appinfo/extended</string>
  <string>appinfo/config</string>
  <string>appinfo/depots</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VdfPropertyType_Object_KnownPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VdfPropertyType_Object_KnownPaths"]));
            }
            set {
                this["VdfPropertyType_Object_KnownPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>appinfo/common/clienttga</string>\r\n  <string>appinfo/common/name</string>\r" +
            "\n  <string>appinfo/common/icon</string>\r\n  <string>appinfo/common/logo</string>\r" +
            "\n  <string>appinfo/common/logo_small</string>\r\n  <string>appinfo/common/clientic" +
            "on</string>\r\n  <string>appinfo/common/metacritic_url</string>\r\n  <string>appinfo" +
            "/common/metacritic_name</string>\r\n  <string>appinfo/common/metacritic_score</str" +
            "ing>\r\n  <string>appinfo/common/metacritic_fullurl</string>\r\n  <string>appinfo/co" +
            "mmon/sortas</string>\r\n  <string>appinfo/common/type</string>\r\n  <string>appinfo/" +
            "common/eulas/\\d+/url</string>\r\n  <string>appinfo/common/eulas/\\d+/id</string>\r\n " +
            " <string>appinfo/common/eulas/\\d+/name</string>\r\n  <string>appinfo/common/steam_" +
            "deck_compatibility/tests/\\d+/token</string>\r\n  <string>appinfo/common/steam_deck" +
            "_compatibility/configuration/supported_input</string>\r\n  <string>appinfo/common/" +
            "steam_deck_compatibility/configuration/recommended_runtime</string>\r\n  <string>a" +
            "ppinfo/common/small_capsule/\\w+</string>\r\n  <string>appinfo/common/header_image/" +
            "\\w+</string>\r\n  <string>appinfo/common/library_assets/library_capsule</string>\r\n" +
            "  <string>appinfo/common/library_assets/library_hero</string>\r\n  <string>appinfo" +
            "/common/library_assets/library_logo</string>\r\n  <string>appinfo/common/library_a" +
            "ssets/logo_position/pinned_position</string>\r\n  <string>appinfo/common/associati" +
            "ons/\\d+/type</string>\r\n  <string>appinfo/common/associations/\\d+/name</string>\r\n" +
            "  <string>appinfo/common/supported_languages/\\w+/supported</string>\r\n  <string>a" +
            "ppinfo/extended/cwdoverride</string>\r\n  <string>appinfo/extended/developer</stri" +
            "ng>\r\n  <string>appinfo/extended/gamedir</string>\r\n  <string>appinfo/extended/hom" +
            "epage</string>\r\n  <string>appinfo/extended/icon</string>\r\n  <string>appinfo/exte" +
            "nded/installscript</string>\r\n  <string>appinfo/extended/launcheula</string>\r\n  <" +
            "string>appinfo/extended/serverbrowsername</string>\r\n  <string>appinfo/extended/s" +
            "tate</string>\r\n  <string>appinfo/extended/developer_url</string>\r\n  <string>appi" +
            "nfo/extended/publisher</string>\r\n  <string>appinfo/extended/gamemanualurl</strin" +
            "g>\r\n  <string>appinfo/config/installdir</string>\r\n  <string>appinfo/config/launc" +
            "h/\\d+/executable</string>\r\n  <string>appinfo/config/launch/\\d+/workingdir</strin" +
            "g>\r\n  <string>appinfo/config/installscriptsignature</string>\r\n  <string>appinfo/" +
            "depots/\\d+/name</string>\r\n  <string>appinfo/depots/\\d+/config/language</string>\r" +
            "\n  <string>appinfo/depots/branches/\\w+/description</string>\r\n  <string>appinfo/u" +
            "fs/savefiles/\\d+/root</string>\r\n  <string>appinfo/ufs/savefiles/\\d+/path</string" +
            ">\r\n  <string>appinfo/ufs/savefiles/\\d+/pattern</string>\r\n  <string>appinfo/ufs/s" +
            "avefiles/\\d+/platforms/\\d+</string>\r\n  <string>appname</string>\r\n  <string>exe</" +
            "string>\r\n  <string>StartDir</string>\r\n  <string>icon</string>\r\n  <string>Shortcu" +
            "tPath</string>\r\n  <string>LaunchOptions</string>\r\n  <string>DevkitGameID</string" +
            ">\r\n  <string>FlatpakAppID</string>\r\n  <string>tags/\\d+</string>\r\n</ArrayOfString" +
            ">")]
        public global::System.Collections.Specialized.StringCollection VdfPropertyType_String_KnownPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VdfPropertyType_String_KnownPaths"]));
            }
            set {
                this["VdfPropertyType_String_KnownPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>appinfo/appid</string>
  <string>appinfo/common/primary_genre</string>
  <string>appinfo/common/gameid</string>
  <string>appinfo/common/review_score</string>
  <string>appinfo/common/review_percentage</string>
  <string>appinfo/common/metacritic_score</string>
  <string>appinfo/common/steam_deck_compatibility/tested_build_id</string>
  <string>appinfo/common/steam_deck_compatibility/tests/\d+/display</string>
  <string>appinfo/common/steam_deck_compatibility/tested_build_id</string>
  <string>appinfo/common/library_assets/logo_position/width_pct</string>
  <string>appinfo/common/library_assets/logo_position/height_pct</string>
  <string>appinfo/common/genres/\d+</string>
  <string>appinfo/common/store_tags/\d+</string>
  <string>appinfo/extended/primarycache</string>
  <string>appinfo/config/contenttype</string>
  <string>appinfo/depots/\d+/maxsize</string>
  <string>appinfo/depots/\d+/manifests/public</string>
  <string>appinfo/depots/branches/\w+/buildid</string>
  <string>appinfo/ufs/quota</string>
  <string>appinfo/ufs/maxnumfiles</string>
  <string>appid</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VdfPropertyType_UInt_KnownPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VdfPropertyType_UInt_KnownPaths"]));
            }
            set {
                this["VdfPropertyType_UInt_KnownPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>appinfo/common/steam_deck_compatibility/configuration/requires_manual_keyb" +
            "oard_invoke</string>\r\n  <string>appinfo/common/steam_deck_compatibility/configur" +
            "ation/requires_non_controller_launcher_nav</string>\r\n  <string>appinfo/common/st" +
            "eam_deck_compatibility/configuration/primary_player_is_controller_slot_0</string" +
            ">\r\n  <string>appinfo/common/steam_deck_compatibility/configuration/non_deck_disp" +
            "lay_glyphs</string>\r\n  <string>appinfo/common/steam_deck_compatibility/configura" +
            "tion/small_text</string>\r\n  <string>appinfo/common/steam_deck_compatibility/conf" +
            "iguration/requires_internet_for_setup</string>\r\n  <string>appinfo/common/steam_d" +
            "eck_compatibility/configuration/requires_internet_for_singleplayer</string>\r\n  <" +
            "string>appinfo/common/steam_deck_compatibility/configuration/requires_h264</stri" +
            "ng>\r\n  <string>appinfo/common/steam_deck_compatibility/configuration/gamescope_f" +
            "rame_limiter_not_supported</string>\r\n  <string>appinfo/common/community_hub_visi" +
            "ble</string>\r\n  <string>appinfo/common/category/category_\\d+</string>\r\n  <string" +
            ">appinfo/common/supported_languages/\\w+/supported</string>\r\n  <string>appinfo/co" +
            "mmon/supported_languages/\\w+/full_audio</string>\r\n  <string>appinfo/extended/nos" +
            "ervers</string>\r\n  <string>appinfo/extended/order</string>\r\n  <string>appinfo/ex" +
            "tended/showcdkeyinmenu</string>\r\n  <string>appinfo/extended/hadthirdpartycdkey</" +
            "string>\r\n  <string>appinfo/config/installscriptoverride</string>\r\n  <string>appi" +
            "nfo/depots/overridescddb</string>\r\n  <string>appinfo/depots/systemdefined</strin" +
            "g>\r\n  <string>appinfo/depots/branches/\\w+/pwdrequired</string>\r\n  <string>appinf" +
            "o/ufs/savefiles/\\d+/recursive</string>\r\n  <string>IsHidden</string>\r\n  <string>A" +
            "llowDesktopConfig</string>\r\n  <string>AllowOverlay</string>\r\n  <string>openvr</s" +
            "tring>\r\n  <string>Devkit</string>\r\n  <string>DevkitOverrideAppID</string>\r\n</Arr" +
            "ayOfString>")]
        public global::System.Collections.Specialized.StringCollection VdfPropertyType_Boolean_KnownPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VdfPropertyType_Boolean_KnownPaths"]));
            }
            set {
                this["VdfPropertyType_Boolean_KnownPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>appinfo/common/steam_deck_compatibility/test_timestamp</string>
  <string>appinfo/common/store_asset_mtime</string>
  <string>appinfo/common/original_release_date</string>
  <string>appinfo/common/steam_release_date</string>
  <string>appinfo/depots/branches/\w+/timeupdated</string>
  <string>LastPlayTime</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VdfPropertyType_RelativeTime_KnownPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VdfPropertyType_RelativeTime_KnownPaths"]));
            }
            set {
                this["VdfPropertyType_RelativeTime_KnownPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlText")]
        public global::System.Drawing.Color VdfDefinition_String_Color {
            get {
                return ((global::System.Drawing.Color)(this["VdfDefinition_String_Color"]));
            }
            set {
                this["VdfDefinition_String_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlText")]
        public global::System.Drawing.Color VdfDefinition_UInt_Color {
            get {
                return ((global::System.Drawing.Color)(this["VdfDefinition_UInt_Color"]));
            }
            set {
                this["VdfDefinition_UInt_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlText")]
        public global::System.Drawing.Color VdfDefinition_Boolean_Color {
            get {
                return ((global::System.Drawing.Color)(this["VdfDefinition_Boolean_Color"]));
            }
            set {
                this["VdfDefinition_Boolean_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlText")]
        public global::System.Drawing.Color VdfDefinition_RelativeTime_Color {
            get {
                return ((global::System.Drawing.Color)(this["VdfDefinition_RelativeTime_Color"]));
            }
            set {
                this["VdfDefinition_RelativeTime_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VdfDefinition_Boolean_FormatAsString {
            get {
                return ((bool)(this["VdfDefinition_Boolean_FormatAsString"]));
            }
            set {
                this["VdfDefinition_Boolean_FormatAsString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string VdfDefinition_Boolean_FalseString {
            get {
                return ((string)(this["VdfDefinition_Boolean_FalseString"]));
            }
            set {
                this["VdfDefinition_Boolean_FalseString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string VdfDefinition_Boolean_TrueString {
            get {
                return ((string)(this["VdfDefinition_Boolean_TrueString"]));
            }
            set {
                this["VdfDefinition_Boolean_TrueString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VdfDefinition_UInt_CultureName {
            get {
                return ((string)(this["VdfDefinition_UInt_CultureName"]));
            }
            set {
                this["VdfDefinition_UInt_CultureName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invariant")]
        public global::SteamGridManager.VdfDefinitionUIntCulture VdfDefinition_UInt_Culture {
            get {
                return ((global::SteamGridManager.VdfDefinitionUIntCulture)(this["VdfDefinition_UInt_Culture"]));
            }
            set {
                this["VdfDefinition_UInt_Culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlText")]
        public global::System.Drawing.Color VdfDefinition_Enum_Color {
            get {
                return ((global::System.Drawing.Color)(this["VdfDefinition_Enum_Color"]));
            }
            set {
                this["VdfDefinition_Enum_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VdfDefinition_RelativeTime_Format {
            get {
                return ((string)(this["VdfDefinition_RelativeTime_Format"]));
            }
            set {
                this["VdfDefinition_RelativeTime_Format"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection VdfPropertyType_Enum_KnownPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VdfPropertyType_Enum_KnownPaths"]));
            }
            set {
                this["VdfPropertyType_Enum_KnownPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WindowTheme {
            get {
                return ((string)(this["WindowTheme"]));
            }
            set {
                this["WindowTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Current")]
        public global::SteamGridManager.VdfDefinitionUIntCulture VdfDefinition_RelativeTime_Culture {
            get {
                return ((global::SteamGridManager.VdfDefinitionUIntCulture)(this["VdfDefinition_RelativeTime_Culture"]));
            }
            set {
                this["VdfDefinition_RelativeTime_Culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DateTimePicker_UseVdfDefinitionFormat {
            get {
                return ((bool)(this["DateTimePicker_UseVdfDefinitionFormat"]));
            }
            set {
                this["DateTimePicker_UseVdfDefinitionFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DateTimePicker_CustomFormat {
            get {
                return ((string)(this["DateTimePicker_CustomFormat"]));
            }
            set {
                this["DateTimePicker_CustomFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Long")]
        public global::System.Windows.Forms.DateTimePickerFormat DateTimePicker_Format {
            get {
                return ((global::System.Windows.Forms.DateTimePickerFormat)(this["DateTimePicker_Format"]));
            }
            set {
                this["DateTimePicker_Format"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string View_List_CustomSortBy {
            get {
                return ((string)(this["View_List_CustomSortBy"]));
            }
            set {
                this["View_List_CustomSortBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightSkyBlue")]
        public global::System.Drawing.Color Details_DragAndDrop_ValidDrop_Color {
            get {
                return ((global::System.Drawing.Color)(this["Details_DragAndDrop_ValidDrop_Color"]));
            }
            set {
                this["Details_DragAndDrop_ValidDrop_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrangeRed")]
        public global::System.Drawing.Color Details_DragAndDrop_InvalidDrop_Color {
            get {
                return ((global::System.Drawing.Color)(this["Details_DragAndDrop_InvalidDrop_Color"]));
            }
            set {
                this["Details_DragAndDrop_InvalidDrop_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Details_Asset_Preview_BackColor_ShowMenu {
            get {
                return ((bool)(this["Details_Asset_Preview_BackColor_ShowMenu"]));
            }
            set {
                this["Details_Asset_Preview_BackColor_ShowMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Details_BackColor {
            get {
                return ((global::System.Drawing.Color)(this["Details_BackColor"]));
            }
            set {
                this["Details_BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::SteamGridManager.AssetAction Details_Asset_MouseRightClickAction {
            get {
                return ((global::SteamGridManager.AssetAction)(this["Details_Asset_MouseRightClickAction"]));
            }
            set {
                this["Details_Asset_MouseRightClickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::SteamGridManager.AssetAction Details_Asset_MouseRightDoubleClickAction {
            get {
                return ((global::SteamGridManager.AssetAction)(this["Details_Asset_MouseRightDoubleClickAction"]));
            }
            set {
                this["Details_Asset_MouseRightDoubleClickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::SteamGridManager.AssetBorder Details_Asset_BorderActivation {
            get {
                return ((global::SteamGridManager.AssetBorder)(this["Details_Asset_BorderActivation"]));
            }
            set {
                this["Details_Asset_BorderActivation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Edit")]
        public global::SteamGridManager.VdfPropertyAction PropertiesDialog_DefaultAction {
            get {
                return ((global::SteamGridManager.VdfPropertyAction)(this["PropertiesDialog_DefaultAction"]));
            }
            set {
                this["PropertiesDialog_DefaultAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Open")]
        public global::SteamGridManager.VdfPropertyAction PropertiesDialog_ObjectAction {
            get {
                return ((global::SteamGridManager.VdfPropertyAction)(this["PropertiesDialog_ObjectAction"]));
            }
            set {
                this["PropertiesDialog_ObjectAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>totalCount</string>
  <string>selectionCount</string>
  <string>status</string>
  <string>dataProvider</string>
  <string>sortBy</string>
  <string>sortOrder</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection List_Status_Part_Order {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["List_Status_Part_Order"]));
            }
            set {
                this["List_Status_Part_Order"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool List_Status_Part_TotalCount {
            get {
                return ((bool)(this["List_Status_Part_TotalCount"]));
            }
            set {
                this["List_Status_Part_TotalCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool List_Status_Part_UnknownAppSubCount {
            get {
                return ((bool)(this["List_Status_Part_UnknownAppSubCount"]));
            }
            set {
                this["List_Status_Part_UnknownAppSubCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool List_Status_Part_AppSubCount {
            get {
                return ((bool)(this["List_Status_Part_AppSubCount"]));
            }
            set {
                this["List_Status_Part_AppSubCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool List_Status_Part_ShortcutSubCount {
            get {
                return ((bool)(this["List_Status_Part_ShortcutSubCount"]));
            }
            set {
                this["List_Status_Part_ShortcutSubCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool List_Status_Part_SelectionCount {
            get {
                return ((bool)(this["List_Status_Part_SelectionCount"]));
            }
            set {
                this["List_Status_Part_SelectionCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool List_Status_Part_Status {
            get {
                return ((bool)(this["List_Status_Part_Status"]));
            }
            set {
                this["List_Status_Part_Status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool List_Status_Part_DataProvider {
            get {
                return ((bool)(this["List_Status_Part_DataProvider"]));
            }
            set {
                this["List_Status_Part_DataProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool List_Status_Part_SortBy {
            get {
                return ((bool)(this["List_Status_Part_SortBy"]));
            }
            set {
                this["List_Status_Part_SortBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool List_Status_Part_SortOrder {
            get {
                return ((bool)(this["List_Status_Part_SortOrder"]));
            }
            set {
                this["List_Status_Part_SortOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Details_Filter_AutoCommit_Delay {
            get {
                return ((int)(this["Details_Filter_AutoCommit_Delay"]));
            }
            set {
                this["Details_Filter_AutoCommit_Delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int List_Filter_AutoCommit_Delay {
            get {
                return ((int)(this["List_Filter_AutoCommit_Delay"]));
            }
            set {
                this["List_Filter_AutoCommit_Delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Details_Filter_AutoCommit_Enable {
            get {
                return ((bool)(this["Details_Filter_AutoCommit_Enable"]));
            }
            set {
                this["Details_Filter_AutoCommit_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool List_Filter_AutoCommit_Enable {
            get {
                return ((bool)(this["List_Filter_AutoCommit_Enable"]));
            }
            set {
                this["List_Filter_AutoCommit_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UI_Language {
            get {
                return ((string)(this["UI_Language"]));
            }
            set {
                this["UI_Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UI_Culture {
            get {
                return ((string)(this["UI_Culture"]));
            }
            set {
                this["UI_Culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Overlays_Path {
            get {
                return ((string)(this["Overlays_Path"]));
            }
            set {
                this["Overlays_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Localization_Path {
            get {
                return ((string)(this["Localization_Path"]));
            }
            set {
                this["Localization_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool List_Menu_VdfColumn_AllowSelectPath {
            get {
                return ((bool)(this["List_Menu_VdfColumn_AllowSelectPath"]));
            }
            set {
                this["List_Menu_VdfColumn_AllowSelectPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool List_Menu_VdfColumn_ShowAllFilters {
            get {
                return ((bool)(this["List_Menu_VdfColumn_ShowAllFilters"]));
            }
            set {
                this["List_Menu_VdfColumn_ShowAllFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Database_AppInfo_AllowSaving {
            get {
                return ((bool)(this["Database_AppInfo_AllowSaving"]));
            }
            set {
                this["Database_AppInfo_AllowSaving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("i")]
        public string Asset_NonSteamAppIcon_NameSuffix {
            get {
                return ((string)(this["Asset_NonSteamAppIcon_NameSuffix"]));
            }
            set {
                this["Asset_NonSteamAppIcon_NameSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Value}")]
        public string PropertyEditor_CopyTextFormat_Single {
            get {
                return ((string)(this["PropertyEditor_CopyTextFormat_Single"]));
            }
            set {
                this["PropertyEditor_CopyTextFormat_Single"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Key} : {Value}")]
        public string PropertyEditor_CopyTextFormat_Many {
            get {
                return ((string)(this["PropertyEditor_CopyTextFormat_Many"]));
            }
            set {
                this["PropertyEditor_CopyTextFormat_Many"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IconConversion_UseClosest {
            get {
                return ((bool)(this["IconConversion_UseClosest"]));
            }
            set {
                this["IconConversion_UseClosest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IconConversion_SaveIconEntry {
            get {
                return ((bool)(this["IconConversion_SaveIconEntry"]));
            }
            set {
                this["IconConversion_SaveIconEntry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IconConversion_SaveIconEntries {
            get {
                return ((bool)(this["IconConversion_SaveIconEntries"]));
            }
            set {
                this["IconConversion_SaveIconEntries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Details_RestoreAppIDAtStart {
            get {
                return ((bool)(this["Details_RestoreAppIDAtStart"]));
            }
            set {
                this["Details_RestoreAppIDAtStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NonSteamAppIcon_AllowDirectLinks {
            get {
                return ((bool)(this["NonSteamAppIcon_AllowDirectLinks"]));
            }
            set {
                this["NonSteamAppIcon_AllowDirectLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NonSteamAppIcon_AutoExtract {
            get {
                return ((bool)(this["NonSteamAppIcon_AutoExtract"]));
            }
            set {
                this["NonSteamAppIcon_AutoExtract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Asset_DeleteAllVariantsBeforeCopy {
            get {
                return ((bool)(this["Asset_DeleteAllVariantsBeforeCopy"]));
            }
            set {
                this["Asset_DeleteAllVariantsBeforeCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Details_WatchFileChanges {
            get {
                return ((bool)(this["Details_WatchFileChanges"]));
            }
            set {
                this["Details_WatchFileChanges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool List_WatchFileChanges {
            get {
                return ((bool)(this["List_WatchFileChanges"]));
            }
            set {
                this["List_WatchFileChanges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Details_WatchFileChangesSimple {
            get {
                return ((bool)(this["Details_WatchFileChangesSimple"]));
            }
            set {
                this["Details_WatchFileChangesSimple"] = value;
            }
        }
    }
}
